In [20]:
import pandas as pd
from dotenv import load_dotenv
from helper import zip_gz, unzip_gz

pd.set_option('display.max_columns', None)

In [2]:
crop_df = pd.read_csv("../data/crop_data.csv")
display(f"Number of rows: {crop_df.shape[0]:,}")
display(crop_df.head())

'Number of rows: 6,980,138'

  COMMODITY_DESC LOCATION_DESC  YEAR  normalized_value
0     SUGARBEETS          OHIO  1983         49.692868
1      SUNFLOWER      NEBRASKA  1993         63.369141
2       SOYBEANS       INDIANA  2014         92.499630
3       SOYBEANS     LOUISIANA  2018         28.906483
4          BEANS      NEW YORK  2007         32.471268

In [3]:
weather_df = pd.read_csv("../data/weather_data.csv")
display(f"Number of rows: {weather_df.shape[0]:,}")
display(weather_df.head())

'Number of rows: 2,250'

,state,year,Q1_cloud_cover.afternoon,Q2_cloud_cover.afternoon,Q3_cloud_cover.afternoon,Q4_cloud_cover.afternoon,Q1_humidity.afternoon,Q2_humidity.afternoon,Q3_humidity.afternoon,Q4_humidity.afternoon,Q1_precipitation.total,Q2_precipitation.total,Q3_precipitation.total,Q4_precipitation.total,Q1_pressure.afternoon,Q2_pressure.afternoon,Q3_pressure.afternoon,Q4_pressure.afternoon,Q1_temperature.afternoon,Q2_temperature.afternoon,Q3_temperature.afternoon,Q4_temperature.afternoon,Q1_temperature.evening,Q2_temperature.evening,Q3_temperature.evening,Q4_temperature.evening,Q1_temperature.max,Q2_temperature.max,Q3_temperature.max,Q4_temperature.max,Q1_temperature.min,Q2_temperature.min,Q3_temperature.min,Q4_temperature.min,Q1_temperature.morning,Q2_temperature.morning,Q3_temperature.morning,Q4_temperature.morning,Q1_temperature.night,Q2_temperature.night,Q3_temperature.night,Q4_temperature.night,Q1_wind.max.direction,Q2_wind.max.direction,Q3_wind.max.direction,Q4_wind.max.direction,Q1_wind.max.speed,Q2_wind.max.speed,Q3_wind.max.speed,Q4_wind.max.speed,is_future
0,Alabama,1980,75.735,44.480000,40.675000,52.151667,67.498333,55.990000,51.900000,50.010000,7.910,0.521667,0.720000,8.493333,1018.783333,1015.763333,1017.626667,1021.670000,286.361667,298.500000,304.888333,286.173333,282.753333,297.846667,302.831667,283.713333,289.098333,300.225000,306.120000,287.851667,277.080000,289.003333,294.598333,278.066667,279.715,289.506667,294.663333,278.710000,283.133333,290.676667,297.231667,280.063333,242.193333,198.683333,188.051667,185.386667,5.151667,3.636667,3.155000,4.641667,0
1,Alabama,1981,47.528,65.207143,48.771667,35.768333,48.048000,45.842857,58.491667,64.810000,0.092,1.904286,0.493333,2.008333,1021.624000,1019.222857,1017.465000,1018.853333,285.976000,299.937143,304.325000,289.721667,284.816000,298.241429,302.431667,286.958333,287.446000,301.040000,305.571667,291.345000,275.494000,289.860000,294.581667,281.140000,276.208,291.344286,294.688333,282.553333,278.474000,293.422857,296.306667,283.935000,221.754000,173.021429,183.100000,99.535000,4.818000,3.534286,2.866667,3.656667,0
2,Alabama,1982,75.294,52.621429,56.115000,71.518333,73.532000,61.824286,65.210000,69.565000,6.532,1.278571,4.346667,5.825000,1017.372000,1017.385714,1019.108333,1018.810000,288.494000,300.655714,302.315000,290.773333,284.844000,299.265714,299.505000,287.768333,290.300000,301.814286,303.241667,291.863333,278.410000,290.955714,293.841667,283.246667,284.428,291.455714,294.195000,286.413333,284.152000,292.308571,295.173333,287.206667,222.838000,185.530000,131.945000,193.718333,4.676000,3.221429,3.026667,5.816667,0
3,Alabama,1983,72.450,53.022857,41.711667,49.433333,59.328000,57.222857,59.598333,64.446667,2.584,4.347143,12.883333,13.058333,1013.456000,1014.522857,1017.653333,1017.681667,286.708000,296.467143,302.270000,285.853333,284.578000,295.565714,300.533333,283.676667,289.176000,298.047143,303.681667,288.960000,276.706000,287.578571,293.071667,278.136667,277.054,288.012857,293.145000,279.373333,279.208000,290.402857,295.193333,282.078333,186.388000,235.011429,151.050000,231.078333,3.550000,4.607143,3.500000,4.715000,0
4,Alabama,1984,33.130,61.528333,52.196667,58.903333,52.585000,54.216667,67.193333,60.461667,0.225,3.033333,9.251667,0.176667,1022.005000,1016.785000,1018.428333,1021.266667,286.011667,296.528333,301.320000,293.081667,284.608333,294.626667,299.466667,290.028333,287.823333,297.743333,302.843333,294.403333,275.708333,288.408333,292.985000,282.556667,276.465,289.130000,293.340000,283.048333,278.455000,291.415000,295.041667,284.205000,260.798333,127.723333,127.528333,162.966667,3.146667,4.155000,2.831667,3.945000,0

In [4]:
weather_df['state'] = weather_df['state'].str.upper()

In [5]:
merged_df = pd.merge(
    crop_df,
    weather_df,
    left_on=['LOCATION_DESC', 'YEAR'],
    right_on=['state', 'year'],
    how='left'
)

merged_df = merged_df.drop(columns=['LOCATION_DESC', 'YEAR'])
merged_df.rename(columns={'COMMODITY_DESC': 'crop', "normalized_value": 'target'}, inplace=True)
merged_df

,crop,target,state,year,Q1_cloud_cover.afternoon,Q2_cloud_cover.afternoon,Q3_cloud_cover.afternoon,Q4_cloud_cover.afternoon,Q1_humidity.afternoon,Q2_humidity.afternoon,Q3_humidity.afternoon,Q4_humidity.afternoon,Q1_precipitation.total,Q2_precipitation.total,Q3_precipitation.total,Q4_precipitation.total,Q1_pressure.afternoon,Q2_pressure.afternoon,Q3_pressure.afternoon,Q4_pressure.afternoon,Q1_temperature.afternoon,Q2_temperature.afternoon,Q3_temperature.afternoon,Q4_temperature.afternoon,Q1_temperature.evening,Q2_temperature.evening,Q3_temperature.evening,Q4_temperature.evening,Q1_temperature.max,Q2_temperature.max,Q3_temperature.max,Q4_temperature.max,Q1_temperature.min,Q2_temperature.min,Q3_temperature.min,Q4_temperature.min,Q1_temperature.morning,Q2_temperature.morning,Q3_temperature.morning,Q4_temperature.morning,Q1_temperature.night,Q2_temperature.night,Q3_temperature.night,Q4_temperature.night,Q1_wind.max.direction,Q2_wind.max.direction,Q3_wind.max.direction,Q4_wind.max.direction,Q1_wind.max.speed,Q2_wind.max.speed,Q3_wind.max.speed,Q4_wind.max.speed,is_future
0,SUGARBEETS,49.692868,OHIO,1983,79.956000,85.078571,33.583333,75.783333,61.276000,60.218571,60.938333,72.506667,0.518000,2.137143,0.121667,5.171667,1016.812000,1014.032857,1020.901667,1016.020000,278.322000,289.802857,298.585000,279.611667,277.742000,289.220000,297.590000,278.628333,280.020000,291.615714,301.328333,282.478333,271.004000,282.747143,289.988333,274.116667,271.326000,283.407143,290.545000,277.128333,272.854000,285.242857,293.526667,277.598333,258.684000,179.662857,100.330000,209.033333,4.438000,5.468571,3.641667,6.576667,0
1,SUNFLOWER,63.369141,NEBRASKA,1993,60.588000,56.170000,58.381667,74.586667,73.786000,60.404286,65.765000,66.870000,2.244000,0.358571,1.763333,5.010000,1022.432000,1017.052857,1014.520000,1010.510000,270.278000,288.237143,295.703333,277.210000,269.896000,289.604286,295.175000,275.900000,272.920000,290.660000,300.201667,280.010000,263.992000,278.321429,287.948333,270.575000,265.858000,279.275714,289.215000,275.023333,266.734000,281.478571,292.601667,274.746667,226.894000,215.285714,229.295000,239.945000,6.430000,6.392857,6.510000,7.516667,0
2,SOYBEANS,92.499630,INDIANA,2014,81.800000,47.142857,57.166667,81.333333,77.400000,55.714286,57.000000,74.000000,2.854000,2.260000,0.406667,3.148333,1018.200000,1017.000000,1018.833333,1020.833333,268.366000,288.944286,294.446667,279.493333,269.174000,290.275714,295.096667,278.613333,270.724000,291.722857,296.636667,281.761667,263.090000,281.867143,285.883333,274.658333,264.788000,282.985714,286.338333,278.291667,267.088000,284.268571,288.990000,279.296667,159.400000,176.714286,232.833333,244.333333,6.336000,6.768571,4.721667,6.720000,0
3,SOYBEANS,28.906483,LOUISIANA,2018,26.600000,32.571429,22.333333,37.166667,63.600000,50.857143,60.500000,66.333333,1.684000,0.770000,3.130000,8.401667,1023.600000,1016.714286,1016.666667,1016.166667,289.450000,300.872857,303.465000,290.373333,289.524000,302.574286,301.640000,289.260000,293.766000,303.715714,305.251667,292.833333,281.936000,289.865714,295.030000,281.745000,283.614000,289.970000,295.111667,283.596667,285.840000,292.857143,296.583333,284.213333,140.000000,200.000000,176.666667,207.833333,6.896000,5.657143,5.140000,6.495000,0
4,BEANS,32.471268,NEW YORK,2007,96.746000,87.227143,32.303333,75.593333,74.488000,59.180000,64.255000,72.713333,8.086000,7.958571,1.821667,5.158333,1010.672000,1011.321429,1015.936667,1018.351667,266.948000,289.395714,295.023333,277.641667,266.926000,287.565714,293.875000,276.646667,268.468000,291.032857,296.515000,279.353333,261.730000,280.285714,286.200000,272.078333,264.066000,282.775714,288.303333,275.016667,265.234000,283.265714,289.266667,276.061667,256.264000,267.052857,235.543333,250.223333,7.066000,3.924286,3.083333,5.781667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6980133,COTTON,63.299809,ALABAMA,2024,53.333333,56.666667,-1.000000,-1.000000,69.000000,66.500000,-1.000000,-1.000000,4.710000,0.596667,-1.000000,-1.000000,1018.000000,1014.666667,-1.000000,-1.000000,285.496667,299.986667,-1.000000,-1.000000,284.585000,301.318333,-1.000000,-1.000000,287.858333,302.458333,-1.000000,-1.000000,278.761667,291.816667,-1.000000,-1.000000,280.256667,292.000000,-1.000000,-1.000000,282.163333,294.275000,-1.000000,-1.000000,255.666667,174.000000,-1.000000,-1.000000,4.370000,3.206667,-1.000000,-1.000000,1
6980134,APPLES,0.000000,VERMONT,2024,69.166667,70.000000,-1.000000,-1.000000,61.166667,66.833333,-1.000000,-1.000000,1.033333,5.331667,-1.000000,-1.000000,1016.500000,1013.833333,-1.000000,-1.000000,271.840000,287.706667,-1.000000,-1.000000,272.836667,288.171667,-1.000000,-1.000000,274.065000,289.848333,-1.000000,-1.000000,265.096667,282.155000,-1.000000,-1.000000,266.560000,282.795000,-1.000000,-1.000000,266.256667,283.876667,-1.000000,-1.000000,283.666667,248.333333,-1.000000,-1.000000,5.355000,5.831667,-1.000000,-1.000000,1
6980135,SOYBEANS,77.026144,SOUTH DAKOTA,2024,40.000000,69.166667,-1.000000,-1.000000,64.166667,63.333333,-1.000000,-1.000000,1.708333,1.011667,-1.000000,-1.000000,1015.500000,1012.333333,-1.000000,-1.000000,275.041667,291.355000,-1.000000,-1.000000,275.461667,293.956667,-1.000000,-1.000000,279.171667,294.971667,-1.000000,-1.000000,268.038333,285.316667,-1.000000,-1.000000,269.925000,286.695000,-1.000000,-1.000000,271.186667,289.310000,-1.000000,-1.000000,222.000000,228.166667,-1.000000,-1.000000,9.615000,10.456667,-1.000000,-1.000000,1
6980136,PEANUTS,60.024911,FLORIDA,2024,75.833333,41.666667,-1.000000,-1.000000,71.500000,63.000000,-1.000000,-1.000000,0.000000,2.780000,-1.000000,-1.000000,1019.000000,1016.500000,-1.000000,-1.000000,296.268333,302.596667,-1.000000,-1.000000,296.348333,302.150000,-1.000000,-1.000000,298.521667,304.786667,-1.000000,-1.000000,286.775000,294.145000,-1.000000,-1.000000,288.083333,294.463333,-1.000000,-1.000000,288.688333,296.558333,-1.000000,-1.000000,228.666667,135.833333,-1.000000,-1.000000,5.720000,5.275000,-1.000000,-1.000000,1
6980137,WHEAT,54.876512,MONTANA,2024,84.666667,48.666667,-1.000000,-1.000000,56.500000,38.000000,-1.000000,-1.000000,0.283333,0.000000,-1.000000,-1.000000,1016.666667,1010.500000,-1.000000,-1.000000,277.320000,290.320000,-1.000000,-1.000000,276.320000,290.820000,-1.000000,-1.000000,280.486667,293.153333,-1.000000,-1.000000,269.486667,280.486667,-1.000000,-1.000000,272.653333,281.153333,-1.000000,-1.000000,274.153333,283.153333,-1.000000,-1.000000,140.000000,265.500000,-1.000000,-1.000000,5.068333,8.200000,-1.000000,-1.000000,1

In [12]:
crops = []
for crop in merged_df['crop'].unique():
    crops.append(crop)

52

In [13]:
wheat_df = merged_df.loc[merged_df['crop'] == "WHEAT"]

In [16]:
high_target = wheat_df.loc[wheat_df['target'] == 100]
high_target

,crop,target,state,year,Q1_cloud_cover.afternoon,Q2_cloud_cover.afternoon,Q3_cloud_cover.afternoon,Q4_cloud_cover.afternoon,Q1_humidity.afternoon,Q2_humidity.afternoon,Q3_humidity.afternoon,Q4_humidity.afternoon,Q1_precipitation.total,Q2_precipitation.total,Q3_precipitation.total,Q4_precipitation.total,Q1_pressure.afternoon,Q2_pressure.afternoon,Q3_pressure.afternoon,Q4_pressure.afternoon,Q1_temperature.afternoon,Q2_temperature.afternoon,Q3_temperature.afternoon,Q4_temperature.afternoon,Q1_temperature.evening,Q2_temperature.evening,Q3_temperature.evening,Q4_temperature.evening,Q1_temperature.max,Q2_temperature.max,Q3_temperature.max,Q4_temperature.max,Q1_temperature.min,Q2_temperature.min,Q3_temperature.min,Q4_temperature.min,Q1_temperature.morning,Q2_temperature.morning,Q3_temperature.morning,Q4_temperature.morning,Q1_temperature.night,Q2_temperature.night,Q3_temperature.night,Q4_temperature.night,Q1_wind.max.direction,Q2_wind.max.direction,Q3_wind.max.direction,Q4_wind.max.direction,Q1_wind.max.speed,Q2_wind.max.speed,Q3_wind.max.speed,Q4_wind.max.speed,is_future
127,WHEAT,100.0,OREGON,2001,79.286000,51.914286,38.186667,83.256667,82.648000,43.495714,55.345000,76.505000,0.844000,0.397143,3.206667,1.600000,1024.194000,1016.997143,1013.016667,1021.668333,269.098000,286.151429,291.110000,274.760000,271.960000,291.087143,296.400000,277.458333,273.554000,291.815714,296.915000,278.881667,262.142000,276.297143,284.218333,270.218333,264.698000,276.612857,284.600000,271.200000,265.748000,281.392857,290.001667,273.438333,222.252000,267.097143,130.555000,197.758333,3.684000,6.234286,5.005000,5.533333,0
168,WHEAT,100.0,OREGON,1995,86.340000,69.454286,14.191667,69.325000,75.714000,54.782857,35.310000,70.628333,1.620000,2.840000,0.353333,5.618333,1015.258000,1011.607143,1016.743333,1015.751667,275.518000,286.245714,292.085000,278.668333,278.840000,288.438571,297.411667,280.343333,279.334000,289.570000,297.878333,282.356667,268.586000,279.214286,281.693333,272.971667,270.610000,280.111429,282.078333,274.798333,270.492000,283.048571,286.605000,274.846667,208.454000,209.200000,209.371667,213.485000,6.076000,6.057143,4.375000,6.115000,0
220,WHEAT,100.0,NEW YORK,2002,96.704000,89.172857,45.511667,99.523333,56.778000,74.127143,64.400000,79.096667,5.592000,6.654286,1.785000,4.233333,1025.560000,1011.328571,1016.600000,1020.798333,275.440000,289.942857,296.165000,277.793333,274.800000,288.958571,293.185000,275.331667,276.594000,291.810000,297.506667,278.290000,268.558000,282.135714,287.763333,272.763333,269.288000,284.955714,290.980000,275.155000,269.544000,284.974286,291.241667,276.223333,164.200000,238.907143,244.020000,286.026667,5.480000,5.007143,4.326667,3.420000,0
224,WHEAT,100.0,VIRGINIA,2004,66.198333,56.401667,60.995000,68.166667,58.975000,57.510000,66.886667,53.543333,5.035000,0.741667,3.170000,0.253333,1018.581667,1020.336667,1016.288333,1017.711667,278.651667,295.896667,299.001667,283.476667,277.665000,297.196667,298.610000,282.268333,280.600000,298.233333,300.885000,285.606667,272.326667,288.478333,292.613333,275.675000,273.625000,288.760000,292.808333,275.970000,275.878333,290.781667,294.580000,278.625000,167.006667,237.563333,129.585000,232.800000,3.896667,3.948333,2.861667,3.005000,0
644,WHEAT,100.0,IDAHO,2000,41.593333,24.775000,11.005000,76.971667,70.775000,33.795000,24.270000,74.706667,1.360000,0.065000,0.003333,1.136667,1022.658333,1013.756667,1014.506667,1024.356667,274.403333,291.103333,298.731667,272.863333,276.236667,294.690000,302.900000,273.226667,277.375000,295.165000,303.221667,274.615000,268.861667,277.861667,283.743333,267.045000,269.790000,278.011667,283.860000,268.065000,272.113333,283.206667,289.940000,269.751667,207.131667,194.531667,243.086667,210.856667,4.291667,5.763333,5.840000,3.951667,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6979029,WHEAT,100.0,COLORADO,2024,30.166667,29.333333,-1.000000,-1.000000,38.000000,48.166667,-1.000000,-1.000000,0.000000,0.770000,-1.000000,-1.000000,1011.833333,1009.500000,-1.000000,-1.000000,282.391667,293.278333,-1.000000,-1.000000,279.666667,292.960000,-1.000000,-1.000000,284.696667,296.901667,-1.000000,-1.000000,266.558333,282.651667,-1.000000,-1.000000,267.675000,283.060000,-1.000000,-1.000000,269.875000,287.401667,-1.000000,-1.000000,272.666667,269.000000,-1.000000,-1.000000,7.398333,9.038333,-1.000000,-1.000000,1
6979111,WHEAT,100.0,NEW MEXICO,2024,54.333333,31.833333,-1.000000,-1.000000,38.833333,18.500000,-1.000000,-1.000000,0.860000,0.750000,-1.000000,-1.000000,1016.333333,1013.333333,-1.000000,-1.000000,283.823333,297.165000,-1.000000,-1.000000,281.661667,297.056667,-1.000000,-1.000000,286.101667,299.501667,-1.000000,-1.000000,271.875000,284.465000,-1.000000,-1.000000,274.091667,286.530000,-1.000000,-1.000000,274.911667,289.473333,-1.000000,-1.000000,224.833333,257.166667,-1.000000,-1.000000,8.940000,8.790000,-1.000000,-1.000000,1
6979772,WHEAT,100.0,NEW YORK,2024,70.000000,53.333333,-1.000000,-1.000000,68.833333,74.833333,-1.000000,-1.000000,1.963333,8.980000,-1.000000,-1.000000,1018.666667,1015.166667,-1.000000,-1.000000,274.723333,290.886667,-1.000000,-1.000000,275.843333,291.671667,-1.000000,-1.000000,277.613333,293.681667,-1.000000,-1.000000,268.536667,284.441667,-1.000000,-1.000000,269.675000,285.075000,-1.000000,-1.000000,270.510000,287.485000,-1.000000,-1.000000,230.000000,200.000000,-1.000000,-1.000000,5.745000,6.173333,-1.000000,-1.000000,1
6979867,WHEAT,100.0,OHIO,2024,81.666667,62.666667,-1.000000,-1.000000,66.000000,70.000000,-1.000000,-1.000000,0.750000,4.108333,-1.000000,-1.000000,1014.833333,1012.333333,-1.000000,-1.000000,277.670000,294.518333,-1.000000,-1.000000,278.540000,296.105000,-1.000000,-1.000000,280.180000,296.860000,-1.000000,-1.000000,271.165000,288.810000,-1.000000,-1.000000,271.756667,289.701667,-1.000000,-1.000000,272.515000,291.780000,-1.000000,-1.000000,220.833333,86.833333,-1.000000,-1.000000,4.350000,4.605000,-1.000000,-1.000000,1
6980099,WHEAT,100.0,MICHIGAN,2024,77.666667,27.000000,-1.000000,-1.000000,68.833333,58.000000,-1.000000,-1.000000,2.650000,0.563333,-1.000000,-1.000000,1014.666667,1014.166667,-1.000000,-1.000000,274.240000,291.341667,-1.000000,-1.000000,274.308333,294.616667,-1.000000,-1.000000,275.881667,295.091667,-1.000000,-1.000000,269.410000,283.346667,-1.000000,-1.000000,270.823333,283.735000,-1.000000,-1.000000,270.958333,287.770000,-1.000000,-1.000000,262.000000,208.166667,-1.000000,-1.000000,7.745000,5.810000,-1.000000,-1.000000,1

In [18]:
states = []
for state in high_target['state'].unique():
    states.append(state)
len(states)

43

In [28]:
total_finished = 0

# Loop through all crops in full dataset
for crop in crops:
    # Store each speciic crop in df drop uneccesary columns
    df = merged_df.loc[merged_df['crop'] == crop]
    df = df.drop(columns=["crop", "state", "year"])

    # Update user when df is ready to be stored
    print(f"{crop.lower()}_df ready")
    zip_gz(df, f"data_per_crop/{crop.lower()}_df.gz")

    # Update percentage and print it out
    total_finished += df.shape[0]
    percentage = (total_finished / merged_df.shape[0]) * 100
    print(f"Progress: {percentage:.2f}%\n")

sugarbeets_df ready
Progress: 0.80%

sunflower_df ready
Progress: 1.82%

soybeans_df ready
Progress: 10.47%

beans_df ready
Progress: 12.64%

sorghum_df ready
Progress: 17.06%

tobacco_df ready
Progress: 18.35%

barley_df ready
Progress: 22.36%

hay_df ready
Progress: 32.10%

oats_df ready
Progress: 36.38%

cotton_df ready
Progress: 41.27%

tomatoes_df ready
Progress: 42.48%

wheat_df ready
Progress: 60.30%

corn_df ready
Progress: 74.09%

pumpkins_df ready
Progress: 74.52%

blackberries_df ready
Progress: 74.87%

squash_df ready
Progress: 75.77%

pecans_df ready
Progress: 76.73%

grapes_df ready
Progress: 77.53%

apples_df ready
Progress: 79.24%

potatoes_df ready
Progress: 81.62%

sweet corn_df ready
Progress: 82.83%

blueberries_df ready
Progress: 83.82%

peanuts_df ready
Progress: 85.31%

grapefruit_df ready
Progress: 85.45%

peas_df ready
Progress: 86.42%

lettuce_df ready
Progress: 87.19%

peaches_df ready
Progress: 88.73%

rye_df ready
Progress: 89.30%

cabbage_df ready
Progress: 89.81%

onions_df ready
Progress: 90.64%

cauliflower_df ready
Progress: 90.80%

raspberries_df ready
Progress: 91.20%

peppers_df ready
Progress: 92.04%

melons_df ready
Progress: 93.05%

pears_df ready
Progress: 94.15%

rice_df ready
Progress: 95.22%

strawberries_df ready
Progress: 95.79%

plums & prunes_df ready
Progress: 96.11%

cherries_df ready
Progress: 96.61%

carrots_df ready
Progress: 96.88%

cucumbers_df ready
Progress: 97.42%

eggplant_df ready
Progress: 97.63%

garlic_df ready
Progress: 97.88%

broccoli_df ready
Progress: 98.14%

beets_df ready
Progress: 98.37%

apricots_df ready
Progress: 98.51%

sugarcane_df ready
Progress: 98.71%

spinach_df ready
Progress: 98.91%

oranges_df ready
Progress: 99.20%

sweet potatoes_df ready
Progress: 99.72%

asparagus_df ready
Progress: 99.93%

lemons_df ready
Progress: 100.00%