In [2]:
import pandas as pd
from helper import zip_gz, unzip_gz

pd.set_option('display.max_columns', None)

In [4]:
crop_df = unzip_gz("data/crop_data.gz")
display(f"Number of rows: {crop_df.shape[0]:,}")
display(crop_df.head())

FileNotFoundError: [Errno 2] No such file or directory: 'data/crop_data.gz'

In [6]:
crop_df['UNIT_DESC'].value_counts()

NameError: name 'crop_df' is not defined

In [4]:
weather_df = pd.read_csv("data/weather_data.csv")
display(f"Number of rows: {weather_df.shape[0]:,}")
display(weather_df.head())

'Number of rows: 2,250'

,state,year,Q1_cloud_cover.afternoon,Q2_cloud_cover.afternoon,Q3_cloud_cover.afternoon,Q4_cloud_cover.afternoon,Q1_humidity.afternoon,Q2_humidity.afternoon,Q3_humidity.afternoon,Q4_humidity.afternoon,Q1_precipitation.total,Q2_precipitation.total,Q3_precipitation.total,Q4_precipitation.total,Q1_pressure.afternoon,Q2_pressure.afternoon,Q3_pressure.afternoon,Q4_pressure.afternoon,Q1_temperature.afternoon,Q2_temperature.afternoon,Q3_temperature.afternoon,Q4_temperature.afternoon,Q1_temperature.evening,Q2_temperature.evening,Q3_temperature.evening,Q4_temperature.evening,Q1_temperature.max,Q2_temperature.max,Q3_temperature.max,Q4_temperature.max,Q1_temperature.min,Q2_temperature.min,Q3_temperature.min,Q4_temperature.min,Q1_temperature.morning,Q2_temperature.morning,Q3_temperature.morning,Q4_temperature.morning,Q1_temperature.night,Q2_temperature.night,Q3_temperature.night,Q4_temperature.night,Q1_wind.max.direction,Q2_wind.max.direction,Q3_wind.max.direction,Q4_wind.max.direction,Q1_wind.max.speed,Q2_wind.max.speed,Q3_wind.max.speed,Q4_wind.max.speed,is_future
0,Alabama,1980,75.735,44.480000,40.675000,52.151667,67.498333,55.990000,51.900000,50.010000,7.910,0.521667,0.720000,8.493333,1018.783333,1015.763333,1017.626667,1021.670000,286.361667,298.500000,304.888333,286.173333,282.753333,297.846667,302.831667,283.713333,289.098333,300.225000,306.120000,287.851667,277.080000,289.003333,294.598333,278.066667,279.715,289.506667,294.663333,278.710000,283.133333,290.676667,297.231667,280.063333,242.193333,198.683333,188.051667,185.386667,5.151667,3.636667,3.155000,4.641667,0
1,Alabama,1981,47.528,65.207143,48.771667,35.768333,48.048000,45.842857,58.491667,64.810000,0.092,1.904286,0.493333,2.008333,1021.624000,1019.222857,1017.465000,1018.853333,285.976000,299.937143,304.325000,289.721667,284.816000,298.241429,302.431667,286.958333,287.446000,301.040000,305.571667,291.345000,275.494000,289.860000,294.581667,281.140000,276.208,291.344286,294.688333,282.553333,278.474000,293.422857,296.306667,283.935000,221.754000,173.021429,183.100000,99.535000,4.818000,3.534286,2.866667,3.656667,0
2,Alabama,1982,75.294,52.621429,56.115000,71.518333,73.532000,61.824286,65.210000,69.565000,6.532,1.278571,4.346667,5.825000,1017.372000,1017.385714,1019.108333,1018.810000,288.494000,300.655714,302.315000,290.773333,284.844000,299.265714,299.505000,287.768333,290.300000,301.814286,303.241667,291.863333,278.410000,290.955714,293.841667,283.246667,284.428,291.455714,294.195000,286.413333,284.152000,292.308571,295.173333,287.206667,222.838000,185.530000,131.945000,193.718333,4.676000,3.221429,3.026667,5.816667,0
3,Alabama,1983,72.450,53.022857,41.711667,49.433333,59.328000,57.222857,59.598333,64.446667,2.584,4.347143,12.883333,13.058333,1013.456000,1014.522857,1017.653333,1017.681667,286.708000,296.467143,302.270000,285.853333,284.578000,295.565714,300.533333,283.676667,289.176000,298.047143,303.681667,288.960000,276.706000,287.578571,293.071667,278.136667,277.054,288.012857,293.145000,279.373333,279.208000,290.402857,295.193333,282.078333,186.388000,235.011429,151.050000,231.078333,3.550000,4.607143,3.500000,4.715000,0
4,Alabama,1984,33.130,61.528333,52.196667,58.903333,52.585000,54.216667,67.193333,60.461667,0.225,3.033333,9.251667,0.176667,1022.005000,1016.785000,1018.428333,1021.266667,286.011667,296.528333,301.320000,293.081667,284.608333,294.626667,299.466667,290.028333,287.823333,297.743333,302.843333,294.403333,275.708333,288.408333,292.985000,282.556667,276.465,289.130000,293.340000,283.048333,278.455000,291.415000,295.041667,284.205000,260.798333,127.723333,127.528333,162.966667,3.146667,4.155000,2.831667,3.945000,0

In [5]:
weather_df['state'] = weather_df['state'].str.upper()

In [6]:
merged_df = pd.merge(
    crop_df,
    weather_df,
    left_on=['LOCATION_DESC', 'YEAR'],
    right_on=['state', 'year'],
    how='left'
)

merged_df = merged_df.drop(columns=['LOCATION_DESC', 'YEAR'])
merged_df.rename(columns={'COMMODITY_DESC': 'crop', "normalized_value": 'target'}, inplace=True)
merged_df

,crop,UNIT_DESC,target,state,year,Q1_cloud_cover.afternoon,Q2_cloud_cover.afternoon,Q3_cloud_cover.afternoon,Q4_cloud_cover.afternoon,Q1_humidity.afternoon,Q2_humidity.afternoon,Q3_humidity.afternoon,Q4_humidity.afternoon,Q1_precipitation.total,Q2_precipitation.total,Q3_precipitation.total,Q4_precipitation.total,Q1_pressure.afternoon,Q2_pressure.afternoon,Q3_pressure.afternoon,Q4_pressure.afternoon,Q1_temperature.afternoon,Q2_temperature.afternoon,Q3_temperature.afternoon,Q4_temperature.afternoon,Q1_temperature.evening,Q2_temperature.evening,Q3_temperature.evening,Q4_temperature.evening,Q1_temperature.max,Q2_temperature.max,Q3_temperature.max,Q4_temperature.max,Q1_temperature.min,Q2_temperature.min,Q3_temperature.min,Q4_temperature.min,Q1_temperature.morning,Q2_temperature.morning,Q3_temperature.morning,Q4_temperature.morning,Q1_temperature.night,Q2_temperature.night,Q3_temperature.night,Q4_temperature.night,Q1_wind.max.direction,Q2_wind.max.direction,Q3_wind.max.direction,Q4_wind.max.direction,Q1_wind.max.speed,Q2_wind.max.speed,Q3_wind.max.speed,Q4_wind.max.speed,is_future
0,SOYBEANS,BU / ACRE,92.499630,INDIANA,2014,81.800000,47.142857,57.166667,81.333333,77.400000,55.714286,57.000000,74.000000,2.854000,2.260000,0.406667,3.148333,1018.200000,1017.000000,1018.833333,1020.833333,268.366000,288.944286,294.446667,279.493333,269.174,290.275714,295.096667,278.613333,270.724000,291.722857,296.636667,281.761667,263.090000,281.867143,285.883333,274.658333,264.788000,282.985714,286.338333,278.291667,267.088000,284.268571,288.990000,279.296667,159.400000,176.714286,232.833333,244.333333,6.336000,6.768571,4.721667,6.720000,0
1,HAY,TONS / ACRE,50.044943,KANSAS,2001,68.810000,52.854286,39.065000,37.093333,67.264000,51.220000,52.243333,57.986667,0.336000,0.365714,3.270000,0.925000,1023.342000,1013.878571,1014.376667,1016.048333,274.178000,295.921429,302.985000,284.311667,274.498,297.711429,303.216667,282.223333,276.212000,298.712857,304.525000,286.096667,267.226000,284.947143,292.420000,275.266667,269.160000,285.697143,292.650000,277.065000,270.836000,288.292857,295.640000,278.895000,227.790000,183.181429,159.025000,221.021667,4.432000,6.967143,6.643333,6.925000,0
2,SUGARBEETS,PCT GOOD,55.783833,IDAHO,2022,57.600000,71.428571,45.833333,66.833333,85.400000,45.285714,19.833333,57.166667,0.074000,1.422857,0.041667,2.838333,1024.400000,1013.285714,1012.500000,1015.833333,272.606000,285.374286,299.225000,277.225000,271.352,289.724286,302.723333,278.481667,275.582000,290.627143,304.420000,280.225000,264.060000,276.325714,288.688333,271.020000,269.030000,277.007143,289.706667,272.813333,269.000000,279.527143,292.025000,273.198333,129.200000,243.857143,249.333333,190.666667,4.392000,6.684286,6.478333,6.130000,0
3,COTTON,PCT EXCELLENT,37.311430,CALIFORNIA,2010,44.892000,19.799286,22.619167,34.735833,61.488000,34.622857,33.133333,48.742500,1.363000,0.057857,0.022500,0.935000,1016.458000,1012.300714,1011.464167,1020.871667,287.117000,295.762857,301.440000,288.748333,289.101,298.063571,305.090000,290.601667,290.465000,299.335000,306.326667,292.448333,280.952000,285.677143,290.865000,280.821667,281.443000,285.705714,291.002500,281.256667,283.479000,289.753571,295.314167,284.502500,166.411000,246.870000,240.011667,198.761667,2.926000,5.459286,4.916667,3.580000,0
4,HAY,TONS / ACRE,33.524074,MINNESOTA,1989,81.054000,61.890000,50.918333,63.275000,67.212000,57.095714,61.031667,65.858333,0.884000,0.902857,0.633333,2.413333,1020.478000,1015.511429,1018.620000,1015.956667,262.922000,289.248571,293.615000,274.963333,262.634,289.297143,294.271667,272.286667,266.890000,291.210000,296.015000,277.366667,254.546000,280.008571,285.245000,264.631667,257.998000,280.924286,285.683333,269.233333,261.906000,282.061429,288.525000,268.506667,213.514000,211.800000,144.498333,131.915000,5.144000,4.612857,4.238333,4.670000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2731131,COTTON,PCT BOLLS OPENING,97.620281,TENNESSEE,2023,99.800000,39.571429,60.166667,24.000000,83.600000,61.285714,75.500000,56.666667,10.274000,3.668571,1.781667,0.063333,1015.800000,1013.285714,1015.666667,1020.666667,284.288000,296.798571,299.495000,289.316667,283.828,295.334286,300.863333,285.896667,286.692000,298.975714,302.570000,290.586667,279.080000,286.745714,293.208333,278.266667,282.242000,288.821429,293.903333,278.860000,282.038000,291.014286,295.115000,280.780000,186.000000,221.571429,204.500000,219.166667,4.560000,5.038571,3.423333,2.843333,0
2731132,CORN,PCT DOUGH,64.399434,KENTUCKY,2023,74.600000,62.000000,62.500000,47.166667,73.800000,62.857143,77.833333,61.333333,5.208000,0.190000,6.785000,0.000000,1015.400000,1010.428571,1017.000000,1021.500000,281.620000,293.617143,297.508333,285.396667,281.550,293.031429,300.398333,284.745000,285.834000,296.872857,301.206667,288.210000,276.358000,286.148571,291.575000,277.173333,279.464000,288.502857,292.555000,278.213333,281.672000,290.541429,293.631667,279.575000,250.000000,220.000000,230.000000,171.166667,6.790000,6.835714,4.716667,4.618333,0
2731133,HAY,TONS / ACRE,100.000000,ARIZONA,2020,1.000000,33.666667,16.166667,15.500000,29.666667,18.333333,21.000000,34.000000,0.000000,0.000000,0.000000,0.000000,1021.166667,1016.500000,1013.333333,1020.333333,285.775000,298.731667,304.206667,286.061667,285.675,298.983333,304.728333,283.768333,288.636667,300.910000,307.233333,289.176667,274.508333,284.171667,289.631667,271.761667,274.791667,284.868333,290.230000,272.895000,277.736667,288.770000,294.475000,275.123333,110.000000,197.500000,222.666667,170.666667,7.533333,6.103333,5.021667,5.045000,0
2731134,SUGARBEETS,PCT HARVESTED,60.076193,NORTH DAKOTA,2023,94.400000,29.714286,43.000000,61.166667,90.400000,55.142857,50.500000,60.333333,0.000000,1.278571,0.521667,0.000000,1019.200000,1014.857143,1015.166667,1025.000000,261.566000,287.798571,294.443333,272.030000,262.896,288.638571,297.716667,271.786667,265.442000,290.862857,298.488333,274.266667,255.816000,278.661429,285.683333,266.680000,257.512000,278.888571,286.153333,268.005000,260.228000,280.842857,288.005000,268.920000,232.400000,212.142857,173.166667,198.000000,6.616000,6.065714,5.923333,6.451667,0
2731135,WHEAT,BU / ACRE,84.964791,INDIANA,2020,61.833333,62.833333,37.000000,86.500000,67.666667,69.500000,64.166667,75.333333,0.408333,3.041667,7.618333,4.438333,1022.666667,1014.333333,1025.500000,1040.333333,276.203333,289.318333,299.900000,282.215000,277.030,289.985000,299.763333,279.433333,278.776667,291.500000,301.585000,284.711667,269.651667,283.426667,290.598333,275.225000,271.171667,284.161667,290.661667,277.623333,271.701667,285.546667,292.376667,279.906667,226.666667,168.833333,176.166667,197.833333,6.333333,6.681667,4.493333,5.780000,0

In [9]:
final_df = merged_df.drop(columns=['UNIT_DESC', 'state'])
final_df.head()

,crop,target,year,Q1_cloud_cover.afternoon,Q2_cloud_cover.afternoon,Q3_cloud_cover.afternoon,Q4_cloud_cover.afternoon,Q1_humidity.afternoon,Q2_humidity.afternoon,Q3_humidity.afternoon,Q4_humidity.afternoon,Q1_precipitation.total,Q2_precipitation.total,Q3_precipitation.total,Q4_precipitation.total,Q1_pressure.afternoon,Q2_pressure.afternoon,Q3_pressure.afternoon,Q4_pressure.afternoon,Q1_temperature.afternoon,Q2_temperature.afternoon,Q3_temperature.afternoon,Q4_temperature.afternoon,Q1_temperature.evening,Q2_temperature.evening,Q3_temperature.evening,Q4_temperature.evening,Q1_temperature.max,Q2_temperature.max,Q3_temperature.max,Q4_temperature.max,Q1_temperature.min,Q2_temperature.min,Q3_temperature.min,Q4_temperature.min,Q1_temperature.morning,Q2_temperature.morning,Q3_temperature.morning,Q4_temperature.morning,Q1_temperature.night,Q2_temperature.night,Q3_temperature.night,Q4_temperature.night,Q1_wind.max.direction,Q2_wind.max.direction,Q3_wind.max.direction,Q4_wind.max.direction,Q1_wind.max.speed,Q2_wind.max.speed,Q3_wind.max.speed,Q4_wind.max.speed,is_future
0,SOYBEANS,92.499630,2014,81.800,47.142857,57.166667,81.333333,77.400,55.714286,57.000000,74.000000,2.854,2.260000,0.406667,3.148333,1018.200,1017.000000,1018.833333,1020.833333,268.366,288.944286,294.446667,279.493333,269.174,290.275714,295.096667,278.613333,270.724,291.722857,296.636667,281.761667,263.090,281.867143,285.883333,274.658333,264.788,282.985714,286.338333,278.291667,267.088,284.268571,288.990000,279.296667,159.400,176.714286,232.833333,244.333333,6.336,6.768571,4.721667,6.720,0
1,HAY,50.044943,2001,68.810,52.854286,39.065000,37.093333,67.264,51.220000,52.243333,57.986667,0.336,0.365714,3.270000,0.925000,1023.342,1013.878571,1014.376667,1016.048333,274.178,295.921429,302.985000,284.311667,274.498,297.711429,303.216667,282.223333,276.212,298.712857,304.525000,286.096667,267.226,284.947143,292.420000,275.266667,269.160,285.697143,292.650000,277.065000,270.836,288.292857,295.640000,278.895000,227.790,183.181429,159.025000,221.021667,4.432,6.967143,6.643333,6.925,0
2,SUGARBEETS,55.783833,2022,57.600,71.428571,45.833333,66.833333,85.400,45.285714,19.833333,57.166667,0.074,1.422857,0.041667,2.838333,1024.400,1013.285714,1012.500000,1015.833333,272.606,285.374286,299.225000,277.225000,271.352,289.724286,302.723333,278.481667,275.582,290.627143,304.420000,280.225000,264.060,276.325714,288.688333,271.020000,269.030,277.007143,289.706667,272.813333,269.000,279.527143,292.025000,273.198333,129.200,243.857143,249.333333,190.666667,4.392,6.684286,6.478333,6.130,0
3,COTTON,37.311430,2010,44.892,19.799286,22.619167,34.735833,61.488,34.622857,33.133333,48.742500,1.363,0.057857,0.022500,0.935000,1016.458,1012.300714,1011.464167,1020.871667,287.117,295.762857,301.440000,288.748333,289.101,298.063571,305.090000,290.601667,290.465,299.335000,306.326667,292.448333,280.952,285.677143,290.865000,280.821667,281.443,285.705714,291.002500,281.256667,283.479,289.753571,295.314167,284.502500,166.411,246.870000,240.011667,198.761667,2.926,5.459286,4.916667,3.580,0
4,HAY,33.524074,1989,81.054,61.890000,50.918333,63.275000,67.212,57.095714,61.031667,65.858333,0.884,0.902857,0.633333,2.413333,1020.478,1015.511429,1018.620000,1015.956667,262.922,289.248571,293.615000,274.963333,262.634,289.297143,294.271667,272.286667,266.890,291.210000,296.015000,277.366667,254.546,280.008571,285.245000,264.631667,257.998,280.924286,285.683333,269.233333,261.906,282.061429,288.525000,268.506667,213.514,211.800000,144.498333,131.915000,5.144,4.612857,4.238333,4.670,0

In [7]:
crops = []
for crop in merged_df['crop'].unique():
    crops.append(crop)

In [11]:
total_finished = 0

# Loop through all crops in full dataset
for crop in crops:
    # Store each speciic crop in df drop uneccesary columns
    df = merged_df.loc[merged_df['crop'] == crop]
    df = df.drop(columns=["crop", "state", "UNIT_DESC"])

    # Update user when df is ready to be stored
    print(f"{crop.lower()}_df ready")
    zip_gz(df, f"data_per_crop/{crop.lower()}_df.gz")

    # Update percentage and print it out
    total_finished += df.shape[0]
    percentage = (total_finished / merged_df.shape[0]) * 100
    print(f"Progress: {percentage:.2f}%\n")

soybeans_df ready
Progress: 10.06%

hay_df ready
Progress: 22.23%

sugarbeets_df ready
Progress: 23.09%

cotton_df ready
Progress: 29.77%

wheat_df ready
Progress: 56.33%

corn_df ready
Progress: 71.68%

oats_df ready
Progress: 76.70%

sorghum_df ready
Progress: 82.41%

peanuts_df ready
Progress: 83.93%

barley_df ready
Progress: 88.61%

peaches_df ready
Progress: 89.42%

peas_df ready
Progress: 89.82%

rice_df ready
Progress: 91.24%

strawberries_df ready
Progress: 91.53%

beans_df ready
Progress: 92.63%

apples_df ready
Progress: 93.51%

cherries_df ready
Progress: 93.60%

potatoes_df ready
Progress: 94.87%

onions_df ready
Progress: 95.24%

tomatoes_df ready
Progress: 95.40%

spinach_df ready
Progress: 95.43%

blueberries_df ready
Progress: 95.86%

melons_df ready
Progress: 96.05%

sweet corn_df ready
Progress: 96.55%

sunflower_df ready
Progress: 97.28%

lettuce_df ready
Progress: 97.35%

rye_df ready
Progress: 97.97%

peppers_df ready
Progress: 98.09%

pears_df ready
Progress: 98.56%

grapefruit_df ready
Progress: 98.57%

sweet potatoes_df ready
Progress: 98.86%

cabbage_df ready
Progress: 98.94%

grapes_df ready
Progress: 99.02%

tobacco_df ready
Progress: 99.56%

pecans_df ready
Progress: 99.65%

sugarcane_df ready
Progress: 99.86%

carrots_df ready
Progress: 99.89%

cucumbers_df ready
Progress: 99.95%

squash_df ready
Progress: 99.98%

oranges_df ready
Progress: 100.00%

In [12]:
zip_gz(final_df, "data/weather_crop_df.gz")